version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "php-docker"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "33062:3306"
    volumes:
      - dbphp-docker:/var/lib/mysql

  projeto:
    links:
     - "db"
    container_name: php-docker
    build:
      context: .
    ports:
      - 9009:80
    volumes:
      - .:/var/www/html
    restart: always
volumes:
  dbphp-docker: